// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/tiger1103/gfast/v3/internal/app/system/dao/internal"
)

// sysAlgorithmDao is the data access object for the table sys_algorithm.
// You can define custom methods on it to extend its functionality as needed.
type sysAlgorithmDao struct {
	*internal.SysAlgorithmDao
}

var (
	// SysAlgorithm is a globally accessible object for table sys_algorithm operations.
	SysAlgorithm = sysAlgorithmDao{internal.NewSysAlgorithmDao()}
)

// Add your custom methods and functionality below.
