// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/tiger1103/gfast/v3/internal/app/system/dao/internal"
)

// sysAnalysisTaskDao is the data access object for the table sys_analysis_task.
// You can define custom methods on it to extend its functionality as needed.
type sysAnalysisTaskDao struct {
	*internal.SysAnalysisTaskDao
}

var (
	// SysAnalysisTask is a globally accessible object for table sys_analysis_task operations.
	SysAnalysisTask = sysAnalysisTaskDao{internal.NewSysAnalysisTaskDao()}
)

// Add your custom methods and functionality below.
