// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/tiger1103/gfast/v3/internal/app/system/dao/internal"
)

// sysAlertConfigDao is the data access object for the table sys_alert_config.
// You can define custom methods on it to extend its functionality as needed.
type sysAlertConfigDao struct {
	*internal.SysAlertConfigDao
}

var (
	// SysAlertConfig is a globally accessible object for table sys_alert_config operations.
	SysAlertConfig = sysAlertConfigDao{internal.NewSysAlertConfigDao()}
)

// Add your custom methods and functionality below.
