// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/tiger1103/gfast/v3/internal/app/system/dao/internal"
)

// sysAlertLogDao is the data access object for the table sys_alert_log.
// You can define custom methods on it to extend its functionality as needed.
type sysAlertLogDao struct {
	*internal.SysAlertLogDao
}

var (
	// SysAlertLog is a globally accessible object for table sys_alert_log operations.
	SysAlertLog = sysAlertLogDao{internal.NewSysAlertLogDao()}
)

// Add your custom methods and functionality below.
