// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/tiger1103/gfast/v3/internal/app/system/dao/internal"
)

// sysCameraDao is the data access object for the table sys_camera.
// You can define custom methods on it to extend its functionality as needed.
type sysCameraDao struct {
	*internal.SysCameraDao
}

var (
	// SysCamera is a globally accessible object for table sys_camera operations.
	SysCamera = sysCameraDao{internal.NewSysCameraDao()}
)

// Add your custom methods and functionality below.
