// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/tiger1103/gfast/v3/internal/app/system/dao/internal"
)

// sysAnalysisTaskCameraAlgorithmDao is the data access object for the table sys_analysis_task_camera_algorithm.
// You can define custom methods on it to extend its functionality as needed.
type sysAnalysisTaskCameraAlgorithmDao struct {
	*internal.SysAnalysisTaskCameraAlgorithmDao
}

var (
	// SysAnalysisTaskCameraAlgorithm is a globally accessible object for table sys_analysis_task_camera_algorithm operations.
	SysAnalysisTaskCameraAlgorithm = sysAnalysisTaskCameraAlgorithmDao{internal.NewSysAnalysisTaskCameraAlgorithmDao()}
)

// Add your custom methods and functionality below.
