// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"

	"github.com/tiger1103/gfast/v3/api/v1/system"
)

type ISysAlgorithm interface {
	List(ctx context.Context, req *system.AlgorithmSearchReq) (res *system.AlgorithmSearchRes, err error)
	Add(ctx context.Context, req *system.AlgorithmAddReq) (err error)
	Edit(ctx context.Context, req *system.AlgorithmEditReq) (err error)
	EditBatch(ctx context.Context, req *system.AlgorithmEditPatchReq) (err error)
	Delete(ctx context.Context, ids []int) (err error)
	Get(ctx context.Context, id int) (res *system.AlgorithmGetRes, err error)
}

var localSysAlgorithm ISysAlgorithm

func SysAlgorithm() ISysAlgorithm {
	if localSysAlgorithm == nil {
		panic("implement not found for interface ISysAlgorithm, forgot register?")
	}
	return localSysAlgorithm
}

func RegisterSysAlgorithm(i ISysAlgorithm) {
	localSysAlgorithm = i
}
