// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"

	"github.com/tiger1103/gfast/v3/api/v1/system"
	"github.com/tiger1103/gfast/v3/internal/app/system/model"
)

type ISysCamera interface {
	List(ctx context.Context, req *system.CameraSearchReq) (res *system.CameraSearchRes, err error)
	Add(ctx context.Context, req *system.CameraAddReq) (err error)
	Edit(ctx context.Context, req *system.CameraEditReq) (err error)
	Delete(ctx context.Context, ids []int) (err error)
	Get(ctx context.Context, id int) (res *model.CameraGetMediaRes, err error)
}

var localSysCamera ISysCamera

func SysCamera() ISysCamera {
	if localSysCamera == nil {
		panic("implement not found for interface ISysCamera, forgot register?")
	}
	return localSysCamera
}

func RegisterSysCamera(i ISysCamera) {
	localSysCamera = i
}
