// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"

	"github.com/tiger1103/gfast/v3/api/v1/system"
	"github.com/tiger1103/gfast/v3/internal/app/system/model/entity"
)

type ISysAlertConfig interface {
	List(ctx context.Context, req *system.AlertConfigSearchReq) (res *system.AlertConfigSearchRes, err error)
	Add(ctx context.Context, req *system.AlertConfigAddReq) (err error)
	Edit(ctx context.Context, req *system.AlertConfigEditReq) (err error)
	Delete(ctx context.Context, ids []int) (err error)
	Get(ctx context.Context, id int) (res *entity.SysAlertConfig, err error)
}

var localSysAlertConfig ISysAlertConfig

func SysAlertConfig() ISysAlertConfig {
	if localSysAlertConfig == nil {
		panic("implement not found for interface ISysAlertConfig, forgot register?")
	}
	return localSysAlertConfig
}

func RegisterSysAlertConfig(i ISysAlertConfig) {
	localSysAlertConfig = i
}
