// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"

	"github.com/tiger1103/gfast/v3/api/v1/system"
	"github.com/tiger1103/gfast/v3/internal/app/system/model/entity"
)

type ISysAlertLog interface {
	List(ctx context.Context, req *system.AlertLogSearchReq) (res *system.AlertLogSearchRes, err error)
	Add(ctx context.Context, req *system.AlertLogAddReq) (err error)
	Edit(ctx context.Context, req *system.AlertLogEditReq) (err error)
	Delete(ctx context.Context, alertIds []int) (err error)
	Get(ctx context.Context, alertId int) (res *entity.SysAlertLog, err error)
	BatchUpdateStatus(ctx context.Context, alertIds []int, status int) (err error)
}

var localSysAlertLog ISysAlertLog

func SysAlertLog() ISysAlertLog {
	if localSysAlertLog == nil {
		panic("implement not found for interface ISysAlertLog, forgot register?")
	}
	return localSysAlertLog
}

func RegisterSysAlertLog(i ISysAlertLog) {
	localSysAlertLog = i
}
