// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"

	"github.com/tiger1103/gfast/v3/api/v1/system"
)

type ISysAnalysisTaskCameraAlgorithm interface {
	List(ctx context.Context, req *system.AnalysisTaskCameraAlgorithmSearchReq) (res *system.AnalysisTaskCameraAlgorithmSearchRes, err error)
	Add(ctx context.Context, req *system.AnalysisTaskCameraAlgorithmAddReq) (err error)
	Edit(ctx context.Context, req *system.AnalysisTaskCameraAlgorithmEditReq) (err error)
	Delete(ctx context.Context, ids []uint) (err error)
	AddBatch(ctx context.Context, req *system.AnalysisTaskCameraAlgorithmAddBatchReq) (err error)
}

var localSysAnalysisTaskCameraAlgorithm ISysAnalysisTaskCameraAlgorithm

func SysAnalysisTaskCameraAlgorithm() ISysAnalysisTaskCameraAlgorithm {
	if localSysAnalysisTaskCameraAlgorithm == nil {
		panic("implement not found for interface ISysAnalysisTaskCameraAlgorithm, forgot register?")
	}
	return localSysAnalysisTaskCameraAlgorithm
}

func RegisterSysAnalysisTaskCameraAlgorithm(i ISysAnalysisTaskCameraAlgorithm) {
	localSysAnalysisTaskCameraAlgorithm = i
}
