// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"

	"github.com/tiger1103/gfast/v3/api/v1/system"
)

type ISysAnalysisTask interface {
	List(ctx context.Context, req *system.AnalysisTaskSearchReq) (res *system.AnalysisTaskSearchRes, err error)
	Add(ctx context.Context, req *system.AnalysisTaskAddReq) (err error)
	Edit(ctx context.Context, req *system.AnalysisTaskEditReq) (err error)
	Delete(ctx context.Context, ids []int) (err error)
	Get(ctx context.Context, id int) (res *system.AnalysisTaskGetRes, err error)
	UpdateState(ctx context.Context, id int, state string) (res *system.AnalysisTaskUpdateStateRes, err error)
}

var localSysAnalysisTask ISysAnalysisTask

func SysAnalysisTask() ISysAnalysisTask {
	if localSysAnalysisTask == nil {
		panic("implement not found for interface ISysAnalysisTask, forgot register?")
	}
	return localSysAnalysisTask
}

func RegisterSysAnalysisTask(i ISysAnalysisTask) {
	localSysAnalysisTask = i
}
